name: "KiCad CI/CD for Spora main board"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'pcb_main/*.sch'
      - 'pcb_main/*.kicad_pcb'
      - 'pcb_main/*.kibot.yaml'
      - 'pcb_main/Makefile'
      - '.github/workflows/spora_main.yml'
  pull_request:
    paths:
      - 'pcb_main/*.sch'
      - 'pcb_main/*.kicad_pcb'
      - 'pcb_main/*.kibot.yaml'
      - 'pcb_main/Makefile'
      - '.github/workflows/spora_main.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      run: |
        make -C pcb_main erc

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: ERC_Output
        path: pcb_main/Fabrication

  DRC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run DRC
      run: |
        make -C pcb_main drc

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: DRC_Output
        path: pcb_main/Fabrication

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run schematic stuff
      run: |
        make -C pcb_main sch_fab

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: FabSch_Output
        path: |
          pcb_main/Fabrication
          pcb_main/kibot_error.log

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: DRC

    steps:
    - uses: actions/checkout@v2

    - name: Run PCB stuff
      run: |
        make -C pcb_main pcb_fab

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: FabPCB_Output
        path: |
          pcb_main/Fabrication
          pcb_main/kibot_error.log


