name: "KiCad CI/CD for Spora I/O"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'pcb_io/*.sch'
      - 'pcb_io/*.kicad_pcb'
      - 'pcb_io/*.kibot.yaml'
      - 'pcb_io/Makefile'
      - '.github/workflows/spora_io.yml'
  pull_request:
    paths:
      - 'pcb_io/*.sch'
      - 'pcb_io/*.kicad_pcb'
      - 'pcb_io/*.kibot.yaml'
      - 'pcb_io/Makefile'
      - '.github/workflows/spora_io.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      run: |
        make -C pcb_io erc

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: ERC_Output
        path: pcb_io/Fabrication

  DRC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run DRC
      run: |
        make -C pcb_io drc

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: DRC_Output
        path: pcb_io/Fabrication

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v2

    - name: Run schematic stuff
      run: |
        make -C pcb_io sch_fab

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: FabSch_Output
        path: |
          pcb_io/Fabrication/
          pcb_io/kibot_error.log
        if-no-files-found: warn

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    needs: DRC

    steps:
    - uses: actions/checkout@v2

    - name: Run PCB stuff
      run: |
        make -C pcb_io pcb_fab

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: FabPCB_Output
        path: |
          pcb_io/Fabrication/
          pcb_io/kibot_error.log
        if-no-files-found: warn

